# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  AWS_REGION: us-east-1

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: yes
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ecs

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "$AWS_KEY and $AWS_SECRET and $CI_ENVIRONMENT_NAME"
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::992382611445:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity 
          aws s3 ls
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:

      - name: Show the variable
        run: echo "$AWS_KEY and $AWS_SECRET and $CI_ENVIRONMENT_NAME"
  
